### ISSUE TITLE
Typo Under Section 4.1 of the Paper

### ISSUE THREAD

**Issue by sugarwaffles** [safouaneelg/copulasimilarity#1]
![image](https://github.com/user-attachments/assets/3d766a43-5e40-4949-a755-dac4000af90d)

I think it is supposed to be "CSIM and ISSM" based on the comparison plots.

**Comment by safouaneelg** [comment]
Hello @sugarwaffles 

Many thanks for the observation. The new pre-print Arxiv release will include this change.

Best,
Safouane
